<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://ServiciosWeb/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="UsuarioWS" targetNamespace="http://ServiciosWeb/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://192.168.1.199:8080/NintySolutions/UsuarioWS?xsd=1" namespace="http://ServiciosWeb/" />
    </xsd:schema>
  </types>
  <message name="crearUsuario">
    <part name="parameters" element="tns:crearUsuario" />
  </message>
  <message name="crearUsuarioResponse">
    <part name="parameters" element="tns:crearUsuarioResponse" />
  </message>
  <portType name="UsuarioWS">
    <operation name="crearUsuario">
      <input wsam:Action="http://ServiciosWeb/UsuarioWS/crearUsuarioRequest" message="tns:crearUsuario" />
      <output wsam:Action="http://ServiciosWeb/UsuarioWS/crearUsuarioResponse" message="tns:crearUsuarioResponse" />
    </operation>
  </portType>
  <binding name="UsuarioWSPortBinding" type="tns:UsuarioWS">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="crearUsuario">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="UsuarioWS">
    <port name="UsuarioWSPort" binding="tns:UsuarioWSPortBinding">
      <soap:address location="http://192.168.1.199:8080/NintySolutions/UsuarioWS" />
    </port>
  </service>
</definitions>